import type { Metadata } from "next";
import { Inter, Poppins, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/store/StoreProvider";
import ClientWrapper from "@/client/ClientWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});


export const metadata: Metadata = {
  title: "3legant.",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-icon.png",
  },
};

import QueryProvider from "@/app/providers/QueryProvider";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${poppins.variable} ${spaceGrotesk.variable} antialiased`} suppressHydrationWarning>
        <ReduxProvider>
          <QueryProvider>
            <ClientWrapper>
              {children}
              <ToastContainer position="top-right" autoClose={2000} style={{ marginTop: "70px" }} />
            </ClientWrapper>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}