// import type { Metadata } from "next";
// import { Inter, Poppins } from "next/font/google";
// import "./globals.css";
// import Navbar from "../components/Navbar";
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
// import Footer from "@/components/footer";
// import NotificationWrapper from "@/client/NotificationWrapper";
// import { CartProvider } from "@/sections/cart/context/CartContext";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100","200","300","400","500","600","700","800","900"],
//   variable: "--font-poppins",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "3legant.",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${inter.variable} ${poppins.variable} antialiased m-auto max-w-[1600px]`}
//       >
        
//         <NotificationWrapper/>
//         <CartProvider>
//         <Navbar />
//         {children}
//         </CartProvider>
//         <Footer/>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter, Poppins , Space_Grotesk } from "next/font/google";
import "./globals.css";
import ClientWrapper from "@/client/ClientWrapper"
import { ProductProvider } from "@/lib/supabase/context/ProductContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-poppins",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300","400","500","600","700"], 
  variable: "--font-space-grotesk",
  display: "swap",
});


export const metadata: Metadata = {
  title: "3legant.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} ${spaceGrotesk.variable} antialiased m-auto max-w-[1600px]`}>
        <ClientWrapper> 
          <ProductProvider>
          {children}
        </ProductProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}