CREATE TABLE IF NOT EXISTS "public"."banners" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" "text",
    "key" "text",
    "category" "text",
    "title" "text",
    "subtitle" "text",
    "image_url" "text" NOT NULL,
    "link_url" "text",
    "position" integer DEFAULT 0,
    "is_active" boolean DEFAULT true,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    PRIMARY KEY ("id"),
    CONSTRAINT "banners_key_key" UNIQUE ("key"),
    CONSTRAINT "banners_name_key" UNIQUE ("name")
);

ALTER TABLE "public"."banners" OWNER TO "postgres";
