CREATE TABLE IF NOT EXISTS "public"."coupons" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" "text" NOT NULL,
    "discount_type" "text",
    "discount_value" numeric NOT NULL,
    "min_order" numeric DEFAULT 0,
    "active" boolean DEFAULT true,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "usage_limit" integer,
    "usage_count" integer DEFAULT 0,
    "expires_at" timestamp without time zone,
    PRIMARY KEY ("id"),
    CONSTRAINT "coupons_code_key" UNIQUE ("code"),
    CONSTRAINT "coupons_discount_type_check" CHECK (("discount_type" = ANY (ARRAY['fixed'::"text", 'percentage'::"text"])))
);

ALTER TABLE "public"."coupons" OWNER TO "postgres";

CREATE INDEX "idx_coupons_active" ON "public"."coupons" USING "btree" ("active");
CREATE INDEX "idx_coupons_expires_at" ON "public"."coupons" USING "btree" ("expires_at");
