CREATE TABLE IF NOT EXISTS "public"."blogs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "title" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "author_name" "text" DEFAULT 'Admin'::"text" NOT NULL,
    "author_image" "text",
    "category" "text" DEFAULT 'General'::"text",
    "excerpt" "text",
    "content" "text" NOT NULL,
    "cover_image" "text",
    "status" "text" DEFAULT 'draft'::"text",
    "published_at" timestamp with time zone,
    PRIMARY KEY ("id"),
    CONSTRAINT "blogs_slug_key" UNIQUE ("slug"),
    CONSTRAINT "blogs_status_check" CHECK (("status" = ANY (ARRAY['draft'::"text", 'published'::"text"])))
);

ALTER TABLE "public"."blogs" OWNER TO "postgres";
