-- Enable RLS for all tables
ALTER TABLE "public"."addresses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."admin_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."blogs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."cart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."cart_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contact_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."coupons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."newsletter_subscribers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."product_variant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."shipping_methods" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."wishlist" ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Admins can answer questions" ON "public"."questions" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1 FROM "public"."profiles" WHERE (("profiles"."id" = "auth"."uid"()) AND ("profiles"."role" = 'admin'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1 FROM "public"."profiles" WHERE (("profiles"."id" = "auth"."uid"()) AND ("profiles"."role" = 'admin'::"text")))));
CREATE POLICY "Allow all access for authenticated admins" ON "public"."blogs" USING (("auth"."role"() = 'authenticated'::"text"));
CREATE POLICY "Allow public read access for published blogs" ON "public"."blogs" FOR SELECT USING (("status" = 'published'::"text"));
CREATE POLICY "Authenticated delete product_variant" ON "public"."product_variant" FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated delete products" ON "public"."products" FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated insert product_variant" ON "public"."product_variant" FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated insert products" ON "public"."products" FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated update product_variant" ON "public"."product_variant" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated update products" ON "public"."products" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Public can read questions" ON "public"."questions" FOR SELECT USING (true);
CREATE POLICY "Public read product_variant" ON "public"."product_variant" FOR SELECT USING (true);
CREATE POLICY "Public read products" ON "public"."products" FOR SELECT USING (true);
CREATE POLICY "Users can delete cart" ON "public"."cart" FOR DELETE USING (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can delete their wishlist" ON "public"."wishlist" FOR DELETE USING (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can insert cart" ON "public"."cart" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can insert questions" ON "public"."questions" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can insert their own profile" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));
CREATE POLICY "Users can insert their wishlist" ON "public"."wishlist" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can update cart" ON "public"."cart" FOR UPDATE USING (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can view their cart" ON "public"."cart" FOR SELECT USING (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can view their wishlist" ON "public"."wishlist" FOR SELECT USING (("auth"."uid"() = "user_id"));
CREATE POLICY "addresses_delete_own" ON "public"."addresses" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));
CREATE POLICY "addresses_insert_own" ON "public"."addresses" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "addresses_owner_delete" ON "public"."addresses" FOR DELETE TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "addresses_owner_insert" ON "public"."addresses" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "addresses_owner_select" ON "public"."addresses" FOR SELECT TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "addresses_owner_update" ON "public"."addresses" FOR UPDATE TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "addresses_select_own" ON "public"."addresses" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));
CREATE POLICY "addresses_service_role_all" ON "public"."addresses" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "addresses_update_own" ON "public"."addresses" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "admin_manage_all_order_items" ON "public"."order_items" TO "authenticated" USING ("public"."app_is_admin"()) WITH CHECK ("public"."app_is_admin"());
CREATE POLICY "admin_manage_all_orders" ON "public"."orders" TO "authenticated" USING ("public"."app_is_admin"()) WITH CHECK ("public"."app_is_admin"());
CREATE POLICY "admin_manage_all_payments" ON "public"."payments" TO "authenticated" USING ("public"."app_is_admin"()) WITH CHECK ("public"."app_is_admin"());
CREATE POLICY "anyone insert contact" ON "public"."contact_messages" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);
CREATE POLICY "anyone insert newsletter" ON "public"."newsletter_subscribers" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);
CREATE POLICY "anyone_insert_contact" ON "public"."contact_messages" FOR INSERT WITH CHECK (true);
CREATE POLICY "anyone_insert_newsletter" ON "public"."newsletter_subscribers" FOR INSERT WITH CHECK (true);
CREATE POLICY "auth insert questions" ON "public"."questions" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "auth insert reviews" ON "public"."reviews" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "auth read coupons" ON "public"."coupons" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "auth_insert_questions" ON "public"."questions" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));
CREATE POLICY "auth_insert_reviews" ON "public"."reviews" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));
CREATE POLICY "cart_items_owner_delete" ON "public"."cart_items" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1 FROM "public"."cart" "c" WHERE (("c"."id" = "cart_items"."cart_id") AND ("c"."user_id" = "auth"."uid"())))));
CREATE POLICY "cart_items_owner_insert" ON "public"."cart_items" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1 FROM "public"."cart" "c" WHERE (("c"."id" = "cart_items"."cart_id") AND ("c"."user_id" = "auth"."uid"())))));
CREATE POLICY "cart_items_owner_select" ON "public"."cart_items" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1 FROM "public"."cart" "c" WHERE (("c"."id" = "cart_items"."cart_id") AND ("c"."user_id" = "auth"."uid"())))));
CREATE POLICY "cart_items_owner_update" ON "public"."cart_items" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1 FROM "public"."cart" "c" WHERE (("c"."id" = "cart_items"."cart_id") AND ("c"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1 FROM "public"."cart" "c" WHERE (("c"."id" = "cart_items"."cart_id") AND ("c"."user_id" = "auth"."uid"())))));
CREATE POLICY "cart_items_service_role_all" ON "public"."cart_items" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "cart_owner_delete" ON "public"."cart" FOR DELETE TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "cart_owner_insert" ON "public"."cart" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "cart_owner_select" ON "public"."cart" FOR SELECT TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "cart_owner_update" ON "public"."cart" FOR UPDATE TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "cart_service_role_all" ON "public"."cart" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "contact_messages_insert_all" ON "public"."contact_messages" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);
CREATE POLICY "contact_messages_service_role_all" ON "public"."contact_messages" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "coupons_admin_all" ON "public"."coupons" TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());
CREATE POLICY "coupons_read_authenticated" ON "public"."coupons" FOR SELECT TO "authenticated" USING (("active" = true));
CREATE POLICY "coupons_service_role_all" ON "public"."coupons" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "newsletter_subscribers_insert_all" ON "public"."newsletter_subscribers" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);
CREATE POLICY "newsletter_subscribers_service_role_all" ON "public"."newsletter_subscribers" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "order_items_owner_delete" ON "public"."order_items" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1 FROM "public"."orders" "o" WHERE (("o"."id" = "order_items"."order_id") AND ("o"."user_id" = "auth"."uid"())))));
CREATE POLICY "order_items_owner_insert" ON "public"."order_items" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1 FROM "public"."orders" "o" WHERE (("o"."id" = "order_items"."order_id") AND ("o"."user_id" = "auth"."uid"())))));
CREATE POLICY "order_items_owner_select" ON "public"."order_items" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1 FROM "public"."orders" "o" WHERE (("o"."id" = "order_items"."order_id") AND ("o"."user_id" = "auth"."uid"())))));
CREATE POLICY "order_items_owner_update" ON "public"."order_items" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1 FROM "public"."orders" "o" WHERE (("o"."id" = "order_items"."order_id") AND ("o"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1 FROM "public"."orders" "o" WHERE (("o"."id" = "order_items"."order_id") AND ("o"."user_id" = "auth"."uid"())))));
CREATE POLICY "order_items_service_role_all" ON "public"."order_items" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "orders_admin_read_all" ON "public"."orders" TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());
CREATE POLICY "orders_owner_delete" ON "public"."orders" FOR DELETE TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "orders_owner_insert" ON "public"."orders" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "orders_owner_select" ON "public"."orders" FOR SELECT TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "orders_owner_update" ON "public"."orders" FOR UPDATE TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "orders_service_role_all" ON "public"."orders" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "own addresses" ON "public"."addresses" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "own cart" ON "public"."cart" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "own cart_items" ON "public"."cart_items" TO "authenticated" USING (("cart_id" IN ( SELECT "cart"."id" FROM "public"."cart" WHERE ("cart"."user_id" = "auth"."uid"())))) WITH CHECK (("cart_id" IN ( SELECT "cart"."id" FROM "public"."cart" WHERE ("cart"."user_id" = "auth"."uid"()))));
CREATE POLICY "own order_items insert" ON "public"."order_items" FOR INSERT TO "authenticated" WITH CHECK (("order_id" IN ( SELECT "orders"."id" FROM "public"."orders" WHERE ("orders"."user_id" = "auth"."uid"()))));
CREATE POLICY "own order_items select" ON "public"."order_items" FOR SELECT TO "authenticated" USING (("order_id" IN ( SELECT "orders"."id" FROM "public"."orders" WHERE ("orders"."user_id" = "auth"."uid"()))));
CREATE POLICY "own orders insert" ON "public"."orders" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "own orders select" ON "public"."orders" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));
CREATE POLICY "own payments insert" ON "public"."payments" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "own payments select" ON "public"."payments" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));
CREATE POLICY "own review update" ON "public"."reviews" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id"));
CREATE POLICY "own wishlist" ON "public"."wishlist" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "payments_owner_insert" ON "public"."payments" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "payments_owner_select" ON "public"."payments" FOR SELECT TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "payments_owner_update" ON "public"."payments" FOR UPDATE TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "payments_service_role_all" ON "public"."payments" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "product_variant_admin_all" ON "public"."product_variant" TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());
CREATE POLICY "product_variant_read_all" ON "public"."product_variant" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "product_variant_service_role_all" ON "public"."product_variant" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "products_admin_all" ON "public"."products" TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());
CREATE POLICY "products_read_all" ON "public"."products" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "products_service_role_all" ON "public"."products" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "profiles_admin_read_all" ON "public"."profiles" FOR SELECT TO "authenticated" USING ("public"."is_admin"());
CREATE POLICY "profiles_owner_insert" ON "public"."profiles" FOR INSERT TO "authenticated" WITH CHECK (("id" = "auth"."uid"()));
CREATE POLICY "profiles_owner_select" ON "public"."profiles" FOR SELECT TO "authenticated" USING (("id" = "auth"."uid"()));
CREATE POLICY "profiles_owner_update" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (("id" = "auth"."uid"())) WITH CHECK (("id" = "auth"."uid"()));
CREATE POLICY "profiles_read_all" ON "public"."profiles" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "profiles_service_role_all" ON "public"."profiles" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "public read product_variant" ON "public"."product_variant" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "public read products" ON "public"."products" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "public read questions" ON "public"."questions" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "public read reviews" ON "public"."reviews" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "public read shipping_methods" ON "public"."shipping_methods" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "public_read_coupons" ON "public"."coupons" FOR SELECT USING (true);
CREATE POLICY "public_read_products" ON "public"."products" FOR SELECT USING (true);
CREATE POLICY "public_read_questions" ON "public"."questions" FOR SELECT USING (true);
CREATE POLICY "public_read_reviews" ON "public"."reviews" FOR SELECT USING (true);
CREATE POLICY "public_read_shipping" ON "public"."shipping_methods" FOR SELECT USING (true);
CREATE POLICY "public_read_variants" ON "public"."product_variant" FOR SELECT USING (true);
CREATE POLICY "questions_owner_delete" ON "public"."questions" FOR DELETE TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "questions_owner_insert" ON "public"."questions" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "questions_owner_update" ON "public"."questions" FOR UPDATE TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "questions_read_all" ON "public"."questions" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "questions_service_role_all" ON "public"."questions" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "reviews_owner_delete" ON "public"."reviews" FOR DELETE TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "reviews_owner_insert" ON "public"."reviews" FOR INSERT TO "authenticated" WITH CHECK ((("user_id" = "auth"."uid"()) OR ("user_id" IS NULL)));
CREATE POLICY "reviews_owner_update" ON "public"."reviews" FOR UPDATE TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "reviews_read_all" ON "public"."reviews" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "reviews_service_role_all" ON "public"."reviews" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "shipping_methods_admin_all" ON "public"."shipping_methods" TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());
CREATE POLICY "shipping_methods_read_all" ON "public"."shipping_methods" FOR SELECT TO "authenticated", "anon" USING (true);
CREATE POLICY "shipping_methods_service_role_all" ON "public"."shipping_methods" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "users_insert_order_items" ON "public"."order_items" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1 FROM "public"."orders" WHERE (("orders"."id" = "order_items"."order_id") AND ("orders"."user_id" = "auth"."uid"())))));
CREATE POLICY "users_insert_orders" ON "public"."orders" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "users_insert_own_profile" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));
CREATE POLICY "users_insert_payments" ON "public"."payments" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "users_read_own_order_items" ON "public"."order_items" FOR SELECT USING ((EXISTS ( SELECT 1 FROM "public"."orders" WHERE (("orders"."id" = "order_items"."order_id") AND ("orders"."user_id" = "auth"."uid"())))));
CREATE POLICY "users_read_own_orders" ON "public"."orders" FOR SELECT USING (("auth"."uid"() = "user_id"));
CREATE POLICY "users_read_own_payments" ON "public"."payments" FOR SELECT USING (("auth"."uid"() = "user_id"));
CREATE POLICY "users_read_own_profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));
CREATE POLICY "users_update_own_profile" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));
CREATE POLICY "wishlist_delete_own" ON "public"."wishlist" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));
CREATE POLICY "wishlist_insert_own" ON "public"."wishlist" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "wishlist_owner_delete" ON "public"."wishlist" FOR DELETE TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "wishlist_owner_insert" ON "public"."wishlist" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "wishlist_owner_select" ON "public"."wishlist" FOR SELECT TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "wishlist_select_own" ON "public"."wishlist" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));
CREATE POLICY "wishlist_service_role_all" ON "public"."wishlist" TO "service_role" USING (true) WITH CHECK (true);

-- Realtime Setup
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";
ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."products";

-- Grants
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."app_is_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."app_is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."app_is_admin"() TO "service_role";
GRANT ALL ON FUNCTION "public"."handle_toggle_user_block"("target_user_id" "uuid", "block_status" boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."handle_toggle_user_block"("target_user_id" "uuid", "block_status" boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_toggle_user_block"("target_user_id" "uuid", "block_status" boolean) TO "service_role";
GRANT ALL ON FUNCTION "public"."handle_toggle_user_role"("target_user_id" "uuid", "new_role" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."handle_toggle_user_role"("target_user_id" "uuid", "new_role" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_toggle_user_role"("target_user_id" "uuid", "new_role" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."is_admin"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."is_admin"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_admin"("user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."update_payments_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_payments_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_payments_updated_at"() TO "service_role";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";

GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "postgres";
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "anon";
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "authenticated";
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "service_role";

GRANT ALL ON ALL SEQUENCES IN SCHEMA "public" TO "postgres";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "public" TO "anon";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "public" TO "authenticated";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "public" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
