CREATE TABLE IF NOT EXISTS "public"."product_variant" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "product_id" bigint NOT NULL REFERENCES "public"."products"("id") ON DELETE CASCADE,
    "sku" "text",
    "color" "text",
    "size" "text",
    "price" double precision DEFAULT 0 NOT NULL,
    "old_price" double precision,
    "stock" integer DEFAULT 0 NOT NULL,
    "thumbnails" "text"[],
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "color_images" "text"[],
    PRIMARY KEY ("id"),
    CONSTRAINT "product_variant_sku_key" UNIQUE ("sku")
);

ALTER TABLE "public"."product_variant" OWNER TO "postgres";

CREATE INDEX "idx_product_variant_created_at" ON "public"."product_variant" USING "btree" ("created_at" DESC);
CREATE INDEX "idx_product_variant_product_id" ON "public"."product_variant" USING "btree" ("product_id");
CREATE INDEX "idx_product_variant_stock" ON "public"."product_variant" USING "btree" ("stock");
